### ISSUE TITLE
`DefaultTax` calculator is applying full additional tax to a discounted (promoted) item if address already present.

### ISSUE THREAD

**Issue by leggers** [spree/spree#4709]
Hello, I'm using the branch `2-2-stable` in a demo, seeded store and seeing an issue where an additional-type tax (i.e. in the US) is being applied to a discounted item's *original price* after a 100% discount using a promotion **if already logged in with an address in the tax zone**. As discussed [in Ryan's blog post](http://ryanbigg.com/2013/09/order-adjustments/), this shouldn't be happening.
Here's a gist with my `Gemfile.lock`: https://gist.github.com/leggers/4395c4eb1b6fd608552a

This bug can be seen here:
![captura de pantalla 2014-05-19 a la s 12 36 45](https://cloud.githubusercontent.com/assets/3916124/3016213/76a138c0-df6b-11e3-9096-c8bf884b4fed.png)

I have a promotion called 'giveaway' set up as follows: 
![captura de pantalla 2014-05-19 a la s 12 07 06](https://cloud.githubusercontent.com/assets/3916124/3015859/548cd4e6-df67-11e3-8be4-5bb269c02fee.png)

It discounts every line item 100% of its price. The same thing happens if it's a whole-order discount of 100% as well. I added free shipping to make the error more apparent.

Repro:
1) Create admin user, go far enough into checkout flow to enter address
2) Create promotion in admin panel.
3) Add item to cart.
4) Enter promotion code.
5) Tax is still taken as if from the original amount, while it should be 0.00.

The same thing happens with a 50% discount. Am I just being an idiot and missing something?

I would love to submit a fix, but after a few hours of burrowing into the code I can't figure out why the tax is being calculated from the non-discounted price. Taking a look into `Spree::Calculator::DefaultTax`, line 31, I see `round_to_two_places(item.discounted_amount * rate.amount)`. Going into the Rails console, `Spree::Order.all[2].line_items[0].discounted_amount.to_f` returns `0.00` but `Spree::Order.all[2].line_items[0].additional_tax_total.to_f` return `1.0`. The tax calculator in the Spree demo app is the `DefaultTax` calculator, as can be seen here: 
![captura de pantalla 2014-05-19 a la s 12 40 08](https://cloud.githubusercontent.com/assets/3916124/3016252/eee5ea06-df6b-11e3-8b26-b009b2345a4c.png)

Could be related to https://github.com/spree/spree/pull/3567 or https://github.com/spree/spree/issues/2493 or https://github.com/spree/spree/pull/2496.

Thank you so much for building and maintaining Spree. Let me know if there's anything I'm not supplying for a proper issue.

**Comment by themgt** [comment]
we're having this problem too. were failing specs ever written for this?

**Comment by JDutil** [comment]
@themgt not that I know of

**Comment by PatLeb** [comment]
This issue affects also versions before 2-2-stable (I've seen it for 2-0-stable and 2-1-stable, but it might be a different beast since there has been a huge refactor in version 2-2). If anyone is interested, there is a fix mentionned in #4760, but it works only for 2-2-stable and later versions.

**Comment by lerkens** [comment]
I ran into this (on 2.2 stable, tax rate not included in the price) From what I can tell, DefaultTax calculates tax per line item, in 2.2. So if you "Create Adjustment" promo the discount is calculated against the order total, but the tax is calculated against the line items, so the tax is wrong. If you create a promo with a "per-line-item-adjustment" both the tax and the promo are calculated per line item and the tax works out.

**Comment by tailic** [comment]
I saw this when using promotions in 2.1 and 2.2. Im currently using the workaround from #4760.

Now I saw it again after creating a negative order adjustment (the user ordered an item an forgot to apply his promotion code) the tax amount was wrong. This is still not fixed in 3.0 and spree is running around with a wrong tax calculation... How can I help with this, some ideas/hints on where to start debugging or maybe someone already looked into the problem but had no time to fix it?

**Comment by code-for-food** [comment]
This is still not fixed in 3.0? Anyone can help on this issue?

Best,

**Comment by vietphanhong** [comment]
I fixed for Spree 3.0 as below. Please comment if it has relative problems:
- `models/spree/order_updater_decorator.rb`:
```ruby
Spree::OrderUpdater.class_eval do
  def update_adjustment_total
    recalculate_adjustments
    order.adjustment_total = line_items.sum(:adjustment_total) +
                             shipments.sum(:adjustment_total)
    order.included_tax_total = line_items.sum(:included_tax_total) + shipments.sum(:included_tax_total)
    order.additional_tax_total = line_items.sum(:additional_tax_total) + shipments.sum(:additional_tax_total)

    order.promo_total = line_items.sum(:promo_total) +
                        shipments.sum(:promo_total)

    update_order_total
  end
end
```
- `models/spree/adjustable/adjustments_updater_decorator.rb`
```ruby
Spree::Adjustable::AdjustmentsUpdater.class_eval do

  def update_promo_adjustments
    promo_adjustments = adjustments.competing_promos.reload.map { |a| a.update!(adjustable) }
    promos_total = promo_adjustments.compact.sum
    choose_best_promo_adjustment unless promos_total == 0
    @promo_total = best_promo_adjustment.try(:amount).to_f

    if adjustable.class.name == 'Spree::LineItem'
      choose_best_order_promo_adjustment(adjustable.order)
      @promo_total += adjustable.amount * @best_order_promo_adjustment.try(:amount).to_f / adjustable.order.item_total if @best_order_promo_adjustment

    end
  end

  def choose_best_order_promo_adjustment(order)
    best_order_promo_adjustment(order)
    if @best_order_promo_adjustment
      other_promotions = order.adjustments.competing_promos.where.not(id: @best_order_promo_adjustment.id)
      other_promotions.update_all(eligible: false)
    end
  end

  def best_order_promo_adjustment(order)
    @best_order_promo_adjustment ||= begin
      order.adjustments.competing_promos.eligible.reorder("amount ASC, created_at DESC, id DESC").first
    end
  end
end
```
- `models/spree/calculator/returns/default_refund_amount_decorator.rb`
```ruby
Spree::Calculator::Returns::DefaultRefundAmount.class_eval do

  def compute(return_item)
    return 0.0.to_d if return_item.exchange_requested?
    inventory_unit = return_item.inventory_unit
    weighted_line_item_pre_tax_amount(inventory_unit).round(2)
  end
end
```

**Comment by aishmita-aggarwal** [comment]
In master branch, the issue is fixed for 'promotion credit adjustment on a line item'. It still does exist for 'promotion credit adjustment on order' and I am looking into it.

**Comment by aishmita-aggarwal** [comment]
In master branch, for the order wide promotion, both guest as well as logged in user are facing this issue.

**Comment by aishmita-aggarwal** [comment]
According to me, both order level promotion and line item level taxation are two separate entities which are not to be mapped on each other.
cc: @priyank-gupta @Mafi88 @damianlegawiec

**Comment by priyank-gupta** [comment]
@aishmita-aggarwal Agreed.
@damianlegawiec @Mafi88 ?

**Comment by jochemsiegel** [comment]
See my comment on [#4760](https://github.com/spree/spree/issues/4760), it seems to me like at least the order level promotion tax issue still exists. Or was this fixed and am I missing something?
